// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_media_error`

Future<RuntimeInfo> runtimeInfo() =>
    PostCraftRust.instance.api.crateApiRuntimeInfo();

Future<PlatformCapabilities> platformCapabilities() =>
    PostCraftRust.instance.api.crateApiPlatformCapabilities();

Future<String> captureTargetReport() =>
    PostCraftRust.instance.api.crateApiCaptureTargetReport();

Future<String> prepareWaylandScreencast({
  required bool includeMicrophone,
  required bool includeSystemAudio,
}) => PostCraftRust.instance.api.crateApiPrepareWaylandScreencast(
  includeMicrophone: includeMicrophone,
  includeSystemAudio: includeSystemAudio,
);

Future<String> startWaylandScreencast({
  required String sessionHandle,
  required String parentWindow,
}) => PostCraftRust.instance.api.crateApiStartWaylandScreencast(
  sessionHandle: sessionHandle,
  parentWindow: parentWindow,
);

Future<String> inspectPipewireTransport() =>
    PostCraftRust.instance.api.crateApiInspectPipewireTransport();

Future<String> probeAuthorizedPipewireStream({required int nodeId}) =>
    PostCraftRust.instance.api.crateApiProbeAuthorizedPipewireStream(
      nodeId: nodeId,
    );

Future<BigInt> recordAuthorizedPipewireStream({
  required int nodeId,
  required int width,
  required int height,
  required int fps,
  required String pixelFormat,
  required String output,
  required BigInt durationMs,
}) => PostCraftRust.instance.api.crateApiRecordAuthorizedPipewireStream(
  nodeId: nodeId,
  width: width,
  height: height,
  fps: fps,
  pixelFormat: pixelFormat,
  output: output,
  durationMs: durationMs,
);

Future<bool> globalShortcutsSupported() =>
    PostCraftRust.instance.api.crateApiGlobalShortcutsSupported();

Future<GlobalShortcutStatus> startGlobalShortcuts({
  required List<ShortcutBinding> bindings,
}) =>
    PostCraftRust.instance.api.crateApiStartGlobalShortcuts(bindings: bindings);

Future<String?> pollGlobalShortcut() =>
    PostCraftRust.instance.api.crateApiPollGlobalShortcut();

Future<void> stopGlobalShortcuts() =>
    PostCraftRust.instance.api.crateApiStopGlobalShortcuts();

Future<String> recordingCapabilities() =>
    PostCraftRust.instance.api.crateApiRecordingCapabilities();

Future<String> startRecordingSession({
  required String output,
  required int width,
  required int height,
  required int fps,
  required bool includeMicrophone,
  required bool includeSystemAudio,
}) => PostCraftRust.instance.api.crateApiStartRecordingSession(
  output: output,
  width: width,
  height: height,
  fps: fps,
  includeMicrophone: includeMicrophone,
  includeSystemAudio: includeSystemAudio,
);

Future<String> stopRecording({required int id}) =>
    PostCraftRust.instance.api.crateApiStopRecording(id: id);

Future<bool> cancelRecording({required int id}) =>
    PostCraftRust.instance.api.crateApiCancelRecording(id: id);

Future<String?> pollRenderSession({required int id}) =>
    PostCraftRust.instance.api.crateApiPollRenderSession(id: id);

Future<int> startTimelineRenderSession({
  required List<String> inputs,
  required List<String> kinds,
  required List<String> sourceInUs,
  required List<String> sourceOutUs,
  required List<String> volumes,
  required String output,
  required String container,
  int? crf,
}) => PostCraftRust.instance.api.crateApiStartTimelineRenderSession(
  inputs: inputs,
  kinds: kinds,
  sourceInUs: sourceInUs,
  sourceOutUs: sourceOutUs,
  volumes: volumes,
  output: output,
  container: container,
  crf: crf,
);

Future<CaptureResult> captureDesktop({
  required String mode,
  String? targetId,
}) => PostCraftRust.instance.api.crateApiCaptureDesktop(
  mode: mode,
  targetId: targetId,
);

Future<String> mediaStatus() =>
    PostCraftRust.instance.api.crateApiMediaStatus();

Future<void> installPanicHook({required String logPath}) =>
    PostCraftRust.instance.api.crateApiInstallPanicHook(logPath: logPath);

Future<ImageOperationResult> pixelateRgba({
  required int width,
  required int height,
  required List<int> rgba,
  required int blockSize,
}) => PostCraftRust.instance.api.crateApiPixelateRgba(
  width: width,
  height: height,
  rgba: rgba,
  blockSize: blockSize,
);

Future<ImageOperationResult> pixelateRegionRgba({
  required int width,
  required int height,
  required List<int> rgba,
  required int left,
  required int top,
  required int regionWidth,
  required int regionHeight,
  required int blockSize,
}) => PostCraftRust.instance.api.crateApiPixelateRegionRgba(
  width: width,
  height: height,
  rgba: rgba,
  left: left,
  top: top,
  regionWidth: regionWidth,
  regionHeight: regionHeight,
  blockSize: blockSize,
);

Future<ImageOperationResult> blurRegionRgba({
  required int width,
  required int height,
  required List<int> rgba,
  required int left,
  required int top,
  required int regionWidth,
  required int regionHeight,
  required int radius,
}) => PostCraftRust.instance.api.crateApiBlurRegionRgba(
  width: width,
  height: height,
  rgba: rgba,
  left: left,
  top: top,
  regionWidth: regionWidth,
  regionHeight: regionHeight,
  radius: radius,
);

Future<Uint8List> generatePosterFrame({
  required String input,
  required int width,
}) => PostCraftRust.instance.api.crateApiGeneratePosterFrame(
  input: input,
  width: width,
);

Future<Float32List> generateWaveformData({
  required String input,
  required BigInt samples,
}) => PostCraftRust.instance.api.crateApiGenerateWaveformData(
  input: input,
  samples: samples,
);

Future<String> probeMediaFile({required String input}) =>
    PostCraftRust.instance.api.crateApiProbeMediaFile(input: input);
