// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class PostCraftRust
    extends
        BaseEntrypoint<
          PostCraftRustApi,
          PostCraftRustApiImpl,
          PostCraftRustWire
        > {
  @internal
  static final instance = PostCraftRust._();

  PostCraftRust._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    PostCraftRustApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required PostCraftRustApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<PostCraftRustApiImpl, PostCraftRustWire>
  get apiImplConstructor => PostCraftRustApiImpl.new;

  @override
  WireConstructor<PostCraftRustWire> get wireConstructor =>
      PostCraftRustWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1092786721;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'postcraft_core',
        ioDirectory: '../../rust/crates/postcraft_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class PostCraftRustApi extends BaseApi {
  Future<ImageOperationResult> crateApiBlurRegionRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int left,
    required int top,
    required int regionWidth,
    required int regionHeight,
    required int radius,
  });

  Future<bool> crateApiCancelRecording({required int id});

  Future<CaptureResult> crateApiCaptureDesktop({required String mode});

  Future<String> crateApiCaptureTargetReport();

  Future<Uint8List> crateApiGeneratePosterFrame({
    required String input,
    required int width,
  });

  Future<Float32List> crateApiGenerateWaveformData({
    required String input,
    required BigInt samples,
  });

  Future<bool> crateApiGlobalShortcutsSupported();

  Future<String> crateApiInspectPipewireTransport();

  Future<ImageOperationResult> crateApiPixelateRegionRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int left,
    required int top,
    required int regionWidth,
    required int regionHeight,
    required int blockSize,
  });

  Future<ImageOperationResult> crateApiPixelateRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int blockSize,
  });

  Future<PlatformCapabilities> crateApiPlatformCapabilities();

  Future<String?> crateApiPollGlobalShortcut();

  Future<String?> crateApiPollRenderSession({required int id});

  Future<String> crateApiPrepareWaylandScreencast({
    required bool includeMicrophone,
    required bool includeSystemAudio,
  });

  Future<String> crateApiProbeAuthorizedPipewireStream({required int nodeId});

  Future<String> crateApiProbeMediaFile({required String input});

  Future<BigInt> crateApiRecordAuthorizedPipewireStream({
    required int nodeId,
    required int width,
    required int height,
    required int fps,
    required String pixelFormat,
    required String output,
    required BigInt durationMs,
  });

  Future<String> crateApiRecordingCapabilities();

  Future<RuntimeInfo> crateApiRuntimeInfo();

  Future<GlobalShortcutStatus> crateApiStartGlobalShortcuts({
    required List<ShortcutBinding> bindings,
  });

  Future<String> crateApiStartRecordingSession({
    required String output,
    required int width,
    required int height,
    required int fps,
    required bool includeMicrophone,
    required bool includeSystemAudio,
  });

  Future<int> crateApiStartTimelineRenderSession({
    required List<String> inputs,
    required List<String> kinds,
    required List<String> sourceInUs,
    required List<String> sourceOutUs,
    required List<String> volumes,
    required String output,
    required String container,
    int? crf,
  });

  Future<String> crateApiStartWaylandScreencast({
    required String sessionHandle,
    required String parentWindow,
  });

  Future<void> crateApiStopGlobalShortcuts();

  Future<String> crateApiStopRecording({required int id});
}

class PostCraftRustApiImpl extends PostCraftRustApiImplPlatform
    implements PostCraftRustApi {
  PostCraftRustApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ImageOperationResult> crateApiBlurRegionRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int left,
    required int top,
    required int regionWidth,
    required int regionHeight,
    required int radius,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(rgba, serializer);
          sse_encode_u_32(left, serializer);
          sse_encode_u_32(top, serializer);
          sse_encode_u_32(regionWidth, serializer);
          sse_encode_u_32(regionHeight, serializer);
          sse_encode_u_32(radius, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_operation_result,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiBlurRegionRgbaConstMeta,
        argValues: [
          width,
          height,
          rgba,
          left,
          top,
          regionWidth,
          regionHeight,
          radius,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBlurRegionRgbaConstMeta => const TaskConstMeta(
    debugName: "blur_region_rgba",
    argNames: [
      "width",
      "height",
      "rgba",
      "left",
      "top",
      "regionWidth",
      "regionHeight",
      "radius",
    ],
  );

  @override
  Future<bool> crateApiCancelRecording({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCancelRecordingConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCancelRecordingConstMeta =>
      const TaskConstMeta(debugName: "cancel_recording", argNames: ["id"]);

  @override
  Future<CaptureResult> crateApiCaptureDesktop({required String mode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_capture_result,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiCaptureDesktopConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureDesktopConstMeta =>
      const TaskConstMeta(debugName: "capture_desktop", argNames: ["mode"]);

  @override
  Future<String> crateApiCaptureTargetReport() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCaptureTargetReportConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCaptureTargetReportConstMeta =>
      const TaskConstMeta(debugName: "capture_target_report", argNames: []);

  @override
  Future<Uint8List> crateApiGeneratePosterFrame({
    required String input,
    required int width,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_u_32(width, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiGeneratePosterFrameConstMeta,
        argValues: [input, width],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGeneratePosterFrameConstMeta =>
      const TaskConstMeta(
        debugName: "generate_poster_frame",
        argNames: ["input", "width"],
      );

  @override
  Future<Float32List> crateApiGenerateWaveformData({
    required String input,
    required BigInt samples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_usize(samples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiGenerateWaveformDataConstMeta,
        argValues: [input, samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateWaveformDataConstMeta =>
      const TaskConstMeta(
        debugName: "generate_waveform_data",
        argNames: ["input", "samples"],
      );

  @override
  Future<bool> crateApiGlobalShortcutsSupported() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGlobalShortcutsSupportedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGlobalShortcutsSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "global_shortcuts_supported",
        argNames: [],
      );

  @override
  Future<String> crateApiInspectPipewireTransport() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInspectPipewireTransportConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectPipewireTransportConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_pipewire_transport",
        argNames: [],
      );

  @override
  Future<ImageOperationResult> crateApiPixelateRegionRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int left,
    required int top,
    required int regionWidth,
    required int regionHeight,
    required int blockSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(rgba, serializer);
          sse_encode_u_32(left, serializer);
          sse_encode_u_32(top, serializer);
          sse_encode_u_32(regionWidth, serializer);
          sse_encode_u_32(regionHeight, serializer);
          sse_encode_u_32(blockSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_operation_result,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiPixelateRegionRgbaConstMeta,
        argValues: [
          width,
          height,
          rgba,
          left,
          top,
          regionWidth,
          regionHeight,
          blockSize,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPixelateRegionRgbaConstMeta => const TaskConstMeta(
    debugName: "pixelate_region_rgba",
    argNames: [
      "width",
      "height",
      "rgba",
      "left",
      "top",
      "regionWidth",
      "regionHeight",
      "blockSize",
    ],
  );

  @override
  Future<ImageOperationResult> crateApiPixelateRgba({
    required int width,
    required int height,
    required List<int> rgba,
    required int blockSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(rgba, serializer);
          sse_encode_u_32(blockSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_operation_result,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiPixelateRgbaConstMeta,
        argValues: [width, height, rgba, blockSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPixelateRgbaConstMeta => const TaskConstMeta(
    debugName: "pixelate_rgba",
    argNames: ["width", "height", "rgba", "blockSize"],
  );

  @override
  Future<PlatformCapabilities> crateApiPlatformCapabilities() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_platform_capabilities,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlatformCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlatformCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "platform_capabilities", argNames: []);

  @override
  Future<String?> crateApiPollGlobalShortcut() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPollGlobalShortcutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollGlobalShortcutConstMeta =>
      const TaskConstMeta(debugName: "poll_global_shortcut", argNames: []);

  @override
  Future<String?> crateApiPollRenderSession({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPollRenderSessionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollRenderSessionConstMeta =>
      const TaskConstMeta(debugName: "poll_render_session", argNames: ["id"]);

  @override
  Future<String> crateApiPrepareWaylandScreencast({
    required bool includeMicrophone,
    required bool includeSystemAudio,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(includeMicrophone, serializer);
          sse_encode_bool(includeSystemAudio, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPrepareWaylandScreencastConstMeta,
        argValues: [includeMicrophone, includeSystemAudio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareWaylandScreencastConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_wayland_screencast",
        argNames: ["includeMicrophone", "includeSystemAudio"],
      );

  @override
  Future<String> crateApiProbeAuthorizedPipewireStream({required int nodeId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(nodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeAuthorizedPipewireStreamConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeAuthorizedPipewireStreamConstMeta =>
      const TaskConstMeta(
        debugName: "probe_authorized_pipewire_stream",
        argNames: ["nodeId"],
      );

  @override
  Future<String> crateApiProbeMediaFile({required String input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiProbeMediaFileConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeMediaFileConstMeta =>
      const TaskConstMeta(debugName: "probe_media_file", argNames: ["input"]);

  @override
  Future<BigInt> crateApiRecordAuthorizedPipewireStream({
    required int nodeId,
    required int width,
    required int height,
    required int fps,
    required String pixelFormat,
    required String output,
    required BigInt durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(nodeId, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(fps, serializer);
          sse_encode_String(pixelFormat, serializer);
          sse_encode_String(output, serializer);
          sse_encode_u_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiRecordAuthorizedPipewireStreamConstMeta,
        argValues: [
          nodeId,
          width,
          height,
          fps,
          pixelFormat,
          output,
          durationMs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecordAuthorizedPipewireStreamConstMeta =>
      const TaskConstMeta(
        debugName: "record_authorized_pipewire_stream",
        argNames: [
          "nodeId",
          "width",
          "height",
          "fps",
          "pixelFormat",
          "output",
          "durationMs",
        ],
      );

  @override
  Future<String> crateApiRecordingCapabilities() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRecordingCapabilitiesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecordingCapabilitiesConstMeta =>
      const TaskConstMeta(debugName: "recording_capabilities", argNames: []);

  @override
  Future<RuntimeInfo> crateApiRuntimeInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_runtime_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInfoConstMeta =>
      const TaskConstMeta(debugName: "runtime_info", argNames: []);

  @override
  Future<GlobalShortcutStatus> crateApiStartGlobalShortcuts({
    required List<ShortcutBinding> bindings,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_shortcut_binding(bindings, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_global_shortcut_status,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiStartGlobalShortcutsConstMeta,
        argValues: [bindings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartGlobalShortcutsConstMeta =>
      const TaskConstMeta(
        debugName: "start_global_shortcuts",
        argNames: ["bindings"],
      );

  @override
  Future<String> crateApiStartRecordingSession({
    required String output,
    required int width,
    required int height,
    required int fps,
    required bool includeMicrophone,
    required bool includeSystemAudio,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(output, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(fps, serializer);
          sse_encode_bool(includeMicrophone, serializer);
          sse_encode_bool(includeSystemAudio, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiStartRecordingSessionConstMeta,
        argValues: [
          output,
          width,
          height,
          fps,
          includeMicrophone,
          includeSystemAudio,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartRecordingSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_recording_session",
        argNames: [
          "output",
          "width",
          "height",
          "fps",
          "includeMicrophone",
          "includeSystemAudio",
        ],
      );

  @override
  Future<int> crateApiStartTimelineRenderSession({
    required List<String> inputs,
    required List<String> kinds,
    required List<String> sourceInUs,
    required List<String> sourceOutUs,
    required List<String> volumes,
    required String output,
    required String container,
    int? crf,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(inputs, serializer);
          sse_encode_list_String(kinds, serializer);
          sse_encode_list_String(sourceInUs, serializer);
          sse_encode_list_String(sourceOutUs, serializer);
          sse_encode_list_String(volumes, serializer);
          sse_encode_String(output, serializer);
          sse_encode_String(container, serializer);
          sse_encode_opt_box_autoadd_i_32(crf, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiStartTimelineRenderSessionConstMeta,
        argValues: [
          inputs,
          kinds,
          sourceInUs,
          sourceOutUs,
          volumes,
          output,
          container,
          crf,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartTimelineRenderSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_timeline_render_session",
        argNames: [
          "inputs",
          "kinds",
          "sourceInUs",
          "sourceOutUs",
          "volumes",
          "output",
          "container",
          "crf",
        ],
      );

  @override
  Future<String> crateApiStartWaylandScreencast({
    required String sessionHandle,
    required String parentWindow,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionHandle, serializer);
          sse_encode_String(parentWindow, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStartWaylandScreencastConstMeta,
        argValues: [sessionHandle, parentWindow],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartWaylandScreencastConstMeta =>
      const TaskConstMeta(
        debugName: "start_wayland_screencast",
        argNames: ["sessionHandle", "parentWindow"],
      );

  @override
  Future<void> crateApiStopGlobalShortcuts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStopGlobalShortcutsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopGlobalShortcutsConstMeta =>
      const TaskConstMeta(debugName: "stop_global_shortcuts", argNames: []);

  @override
  Future<String> crateApiStopRecording({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_native_error,
        ),
        constMeta: kCrateApiStopRecordingConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopRecordingConstMeta =>
      const TaskConstMeta(debugName: "stop_recording", argNames: ["id"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CaptureResult dco_decode_capture_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CaptureResult(
      path: dco_decode_String(arr[0]),
      mode: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GlobalShortcutStatus dco_decode_global_shortcut_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GlobalShortcutStatus(
      supported: dco_decode_bool(arr[0]),
      requestedIds: dco_decode_list_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageOperationResult dco_decode_image_operation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImageOperationResult(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ShortcutBinding> dco_decode_list_shortcut_binding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shortcut_binding).toList();
  }

  @protected
  NativeError dco_decode_native_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformCapabilities dco_decode_platform_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PlatformCapabilities(
      desktopCapture: dco_decode_bool(arr[0]),
      windowCapture: dco_decode_bool(arr[1]),
      systemAudioCapture: dco_decode_bool(arr[2]),
      globalShortcuts: dco_decode_bool(arr[3]),
      clipboardImageWrite: dco_decode_bool(arr[4]),
      waylandScreencast: dco_decode_bool(arr[5]),
      microphoneCapture: dco_decode_bool(arr[6]),
      captureReason: dco_decode_String(arr[7]),
    );
  }

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RuntimeInfo(
      version: dco_decode_String(arr[0]),
      platform: dco_decode_String(arr[1]),
    );
  }

  @protected
  ShortcutBinding dco_decode_shortcut_binding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ShortcutBinding(
      id: dco_decode_String(arr[0]),
      preferredTrigger: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  CaptureResult sse_decode_capture_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_mode = sse_decode_String(deserializer);
    return CaptureResult(path: var_path, mode: var_mode);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GlobalShortcutStatus sse_decode_global_shortcut_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_supported = sse_decode_bool(deserializer);
    var var_requestedIds = sse_decode_list_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return GlobalShortcutStatus(
      supported: var_supported,
      requestedIds: var_requestedIds,
      message: var_message,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageOperationResult sse_decode_image_operation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return ImageOperationResult(
      width: var_width,
      height: var_height,
      rgba: var_rgba,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ShortcutBinding> sse_decode_list_shortcut_binding(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ShortcutBinding>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shortcut_binding(deserializer));
    }
    return ans_;
  }

  @protected
  NativeError sse_decode_native_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return NativeError(code: var_code, message: var_message);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformCapabilities sse_decode_platform_capabilities(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_desktopCapture = sse_decode_bool(deserializer);
    var var_windowCapture = sse_decode_bool(deserializer);
    var var_systemAudioCapture = sse_decode_bool(deserializer);
    var var_globalShortcuts = sse_decode_bool(deserializer);
    var var_clipboardImageWrite = sse_decode_bool(deserializer);
    var var_waylandScreencast = sse_decode_bool(deserializer);
    var var_microphoneCapture = sse_decode_bool(deserializer);
    var var_captureReason = sse_decode_String(deserializer);
    return PlatformCapabilities(
      desktopCapture: var_desktopCapture,
      windowCapture: var_windowCapture,
      systemAudioCapture: var_systemAudioCapture,
      globalShortcuts: var_globalShortcuts,
      clipboardImageWrite: var_clipboardImageWrite,
      waylandScreencast: var_waylandScreencast,
      microphoneCapture: var_microphoneCapture,
      captureReason: var_captureReason,
    );
  }

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    return RuntimeInfo(version: var_version, platform: var_platform);
  }

  @protected
  ShortcutBinding sse_decode_shortcut_binding(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_preferredTrigger = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return ShortcutBinding(
      id: var_id,
      preferredTrigger: var_preferredTrigger,
      description: var_description,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_capture_result(CaptureResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.mode, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_global_shortcut_status(
    GlobalShortcutStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.supported, serializer);
    sse_encode_list_String(self.requestedIds, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_operation_result(
    ImageOperationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_shortcut_binding(
    List<ShortcutBinding> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shortcut_binding(item, serializer);
    }
  }

  @protected
  void sse_encode_native_error(NativeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_platform_capabilities(
    PlatformCapabilities self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.desktopCapture, serializer);
    sse_encode_bool(self.windowCapture, serializer);
    sse_encode_bool(self.systemAudioCapture, serializer);
    sse_encode_bool(self.globalShortcuts, serializer);
    sse_encode_bool(self.clipboardImageWrite, serializer);
    sse_encode_bool(self.waylandScreencast, serializer);
    sse_encode_bool(self.microphoneCapture, serializer);
    sse_encode_String(self.captureReason, serializer);
  }

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.platform, serializer);
  }

  @protected
  void sse_encode_shortcut_binding(
    ShortcutBinding self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.preferredTrigger, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
