// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CaptureResult {
  final String path;
  final String mode;

  const CaptureResult({required this.path, required this.mode});

  @override
  int get hashCode => path.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          mode == other.mode;
}

/// Outcome of a global-shortcut registration request.
class GlobalShortcutStatus {
  final bool supported;
  final List<String> requestedIds;
  final String message;

  const GlobalShortcutStatus({
    required this.supported,
    required this.requestedIds,
    required this.message,
  });

  @override
  int get hashCode =>
      supported.hashCode ^ requestedIds.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlobalShortcutStatus &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          requestedIds == other.requestedIds &&
          message == other.message;
}

class ImageOperationResult {
  final int width;
  final int height;
  final Uint8List rgba;

  const ImageOperationResult({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageOperationResult &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

class NativeError implements FrbException {
  final String code;
  final String message;

  const NativeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class PlatformCapabilities {
  final bool desktopCapture;
  final bool windowCapture;
  final bool systemAudioCapture;
  final bool globalShortcuts;
  final bool clipboardImageWrite;
  final bool waylandScreencast;
  final bool microphoneCapture;
  final String captureReason;

  const PlatformCapabilities({
    required this.desktopCapture,
    required this.windowCapture,
    required this.systemAudioCapture,
    required this.globalShortcuts,
    required this.clipboardImageWrite,
    required this.waylandScreencast,
    required this.microphoneCapture,
    required this.captureReason,
  });

  @override
  int get hashCode =>
      desktopCapture.hashCode ^
      windowCapture.hashCode ^
      systemAudioCapture.hashCode ^
      globalShortcuts.hashCode ^
      clipboardImageWrite.hashCode ^
      waylandScreencast.hashCode ^
      microphoneCapture.hashCode ^
      captureReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformCapabilities &&
          runtimeType == other.runtimeType &&
          desktopCapture == other.desktopCapture &&
          windowCapture == other.windowCapture &&
          systemAudioCapture == other.systemAudioCapture &&
          globalShortcuts == other.globalShortcuts &&
          clipboardImageWrite == other.clipboardImageWrite &&
          waylandScreencast == other.waylandScreencast &&
          microphoneCapture == other.microphoneCapture &&
          captureReason == other.captureReason;
}

class RuntimeInfo {
  final String version;
  final String platform;

  const RuntimeInfo({required this.version, required this.platform});

  @override
  int get hashCode => version.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          platform == other.platform;
}

/// A single portal global-shortcut binding request.
class ShortcutBinding {
  final String id;
  final String preferredTrigger;
  final String description;

  const ShortcutBinding({
    required this.id,
    required this.preferredTrigger,
    required this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^ preferredTrigger.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShortcutBinding &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          preferredTrigger == other.preferredTrigger &&
          description == other.description;
}
